# Generated by Django 3.1.1 on 2022-01-11 14:57

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('postbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/pay/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/soft/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('color', models.CharField(choices=[('blue_bg.jpg', 'Blue'), ('purple_bg.jpg', 'Purple'), ('red_bg.jpg', 'Red'), ('green_bg.jpg', 'Green'), ('yellow_bg.jpg', 'Yellow'), ('azure_bg.jpg', 'Azure'), ('orange_bg.jpg', 'Orange')], max_length=50, verbose_name='Color Background')),
                ('trust_score', models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Trust & Fairness Score')),
                ('license', models.CharField(choices=[('1', 'Curacao'), ('2', 'Malta')], default=2, max_length=3, verbose_name='License')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/logos/', verbose_name='Casino Logo')),
                ('position_en', models.IntegerField(default=0, verbose_name='Position EN')),
                ('link_en', models.CharField(blank=True, help_text='Если в ссылке уже есть знак ? то она должна оканчиваться на знак &, если нет, то на знак ?', max_length=180, null=True, verbose_name='Link EN')),
                ('adv1_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN')),
                ('adv2_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN')),
                ('adv3_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN')),
                ('position_au', models.IntegerField(default=0, verbose_name='Position AU')),
                ('link_au', models.CharField(blank=True, help_text='Если в ссылке уже есть знак ? то она должна оканчиваться на знак &, если нет, то на знак ?', max_length=180, null=True, verbose_name='Link AU')),
                ('adv1_au', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 AU')),
                ('adv2_au', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 AU')),
                ('adv3_au', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 AU')),
                ('min_dep', models.IntegerField(default=0, verbose_name='Min deposit')),
                ('bonus', models.IntegerField(default=0, verbose_name='Welcome bonus')),
                ('limit', models.IntegerField(default=0, verbose_name='Bonus limit')),
                ('fs', models.IntegerField(default=0, verbose_name='Free Spins')),
                ('country', models.ManyToManyField(blank=True, default=None, related_name='countries', to='geo.Countries')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff', to='postbacks.partner')),
                ('pay_au', models.ManyToManyField(blank=True, related_name='pays_au', to='casinos.Payment')),
                ('pay_en', models.ManyToManyField(blank=True, related_name='pays_en', to='casinos.Payment')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
            },
        ),
    ]
