# Generated by Django 3.1.1 on 2022-01-26 09:51

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('postbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('color', models.CharField(blank=True, choices=[('blue-band.png', 'Blue'), ('darkblue-band.png', 'DarkBlue'), ('red-band.png', 'Red'), ('green-band.png', 'Green'), ('yellow-band.png', 'Yellow'), ('violet-band.png', 'Violet'), ('purple-band.png', 'Purple'), ('orange-band.png', 'Orange')], max_length=50, null=True, verbose_name='Color')),
                ('text', models.CharField(blank=True, max_length=10, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/pay/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/soft/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('trust_score', models.CharField(choices=[('50', '5.0'), ('49', '4.9'), ('48', '4.8'), ('47', '4.7'), ('46', '4.6'), ('45', '4.5'), ('44', '4.4'), ('43', '4.3'), ('42', '4.2'), ('41', '4.1'), ('40', '4.0'), ('35', '3.5'), ('30', '3.0'), ('25', '2.5'), ('20', '2.0'), ('15', '1.5'), ('10', '1.0'), ('0', '0.0')], max_length=3, verbose_name='Trust & Fairness Score')),
                ('votes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating Votes')),
                ('license', models.CharField(choices=[('1', 'Curacao'), ('2', 'Malta')], default=2, max_length=3, verbose_name='License')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/logos/', verbose_name='Casino Logo')),
                ('position', models.IntegerField(default=0, verbose_name='Position AU')),
                ('link', models.CharField(blank=True, help_text='Если в ссылке уже есть знак ? то она должна оканчиваться на знак &, если нет, то на знак ?', max_length=180, null=True, verbose_name='Link AU')),
                ('adv1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 AU')),
                ('adv2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 AU')),
                ('adv3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 AU')),
                ('min_dep', models.IntegerField(default=0, verbose_name='Min deposit')),
                ('bonus', models.IntegerField(default=0, verbose_name='Welcome bonus')),
                ('limit', models.IntegerField(default=0, verbose_name='Bonus limit')),
                ('cashback', models.IntegerField(default=0, verbose_name='CashBack %')),
                ('fs', models.IntegerField(default=0, verbose_name='Free Spins')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casino_badge', to='casinos.badge')),
                ('country', models.ManyToManyField(blank=True, default=None, related_name='countries', to='geo.Countries')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff', to='postbacks.partner')),
                ('pay', models.ManyToManyField(blank=True, related_name='pays_au', to='casinos.Payment')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
            },
        ),
    ]
