# Generated by Django 3.1.1 on 2022-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='adv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='link',
            field=models.CharField(blank=True, help_text='Если в ссылке уже есть знак ? то она должна оканчиваться на знак &, если нет, то на знак ?', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='pay',
            field=models.ManyToManyField(blank=True, related_name='pays', to='casinos.Payment'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
