# Generated by Django 3.1.1 on 2022-01-11 15:18

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('text', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/soft/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
    ]
