# Generated by Django 3.1.1 on 2022-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='color',
        ),
        migrations.AlterField(
            model_name='badge',
            name='text',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='name'),
        ),
    ]
