# Generated by Django 3.1.1 on 2022-01-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_auto_20220126_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='license',
            field=models.CharField(choices=[('1', 'Curacao'), ('2', 'Malta'), ('3', 'AAMS')], default=2, max_length=3, verbose_name='License'),
        ),
    ]
