# Generated by Django 3.1.1 on 2022-01-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0003_auto_20220126_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='real_position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Real Position'),
        ),
    ]
