# Generated by Django 3.1.1 on 2022-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0003_auto_20220113_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(blank=True, choices=[('blue_bg.jpg', 'Blue'), ('purple_bg.jpg', 'Purple'), ('red_bg.jpg', 'Red'), ('green_bg.jpg', 'Green'), ('yellow_bg.jpg', 'Yellow'), ('azure_bg.jpg', 'Azure'), ('orange_bg.jpg', 'Orange')], max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='text',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Text'),
        ),
    ]
