# Generated by Django 3.1.1 on 2022-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_auto_20220113_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(blank=True, choices=[('blue-band.jpg', 'Blue'), ('darkblue-band.jpg', 'DarkBlue'), ('red-band.jpg', 'Red'), ('green-band.jpg', 'Green'), ('yellow-band.jpg', 'Yellow'), ('violet-band.jpg', 'Violet'), ('purple-band.jpg', 'Purple'), ('orange-band.jpg', 'Orange')], max_length=50, null=True, verbose_name='Color'),
        ),
    ]
