# Generated by Django 3.1.1 on 2022-01-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_casino_real_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='top_position',
            field=models.CharField(blank=True, choices=[('1', 'First'), ('2', 'Second')], default=2, max_length=3, null=True, verbose_name='Top position'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='real_position',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Real Position'),
        ),
    ]
