# Generated by Django 3.1.1 on 2022-01-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0005_auto_20220114_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casino_badge', to='casinos.badge'),
        ),
    ]
