# Generated by Django 3.1.1 on 2022-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0006_casino_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(blank=True, choices=[('blue-band.png', 'Blue'), ('darkblue-band.png', 'DarkBlue'), ('red-band.png', 'Red'), ('green-band.png', 'Green'), ('yellow-band.png', 'Yellow'), ('violet-band.png', 'Violet'), ('purple-band.png', 'Purple'), ('orange-band.png', 'Orange')], max_length=50, null=True, verbose_name='Color'),
        ),
    ]
