# Generated by Django 3.1.1 on 2022-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0007_auto_20220114_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating Votes'),
        ),
    ]
