# Generated by Django 3.1.1 on 2022-01-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0008_casino_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='adv1_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv2_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='adv3_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='pay_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_en',
        ),
    ]
