# Generated by Django 3.1.1 on 2022-01-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0009_auto_20220118_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='adv1_au',
            new_name='adv1',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='adv2_au',
            new_name='adv2',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='adv3_au',
            new_name='adv3',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='link_au',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='pay_au',
            new_name='pay',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='position_au',
            new_name='position',
        ),
    ]
