# Generated by Django 3.1.1 on 2022-01-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postbacks', '0002_auto_20220121_1416'),
        ('casinos', '0010_auto_20220118_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='partner',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aff', to='postbacks.partner'),
        ),
    ]
