# Generated by Django 3.1.1 on 2022-01-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0012_auto_20220121_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='cashback',
            field=models.IntegerField(default=0, verbose_name='CashBack %'),
        ),
    ]
