# Generated by Django 3.1.1 on 2022-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postback',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
