# Generated by Django 3.1.1 on 2022-01-26 09:51

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('acronym', models.CharField(default=None, max_length=5, null=True, verbose_name='acronym')),
                ('symbol', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='symbol')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/currency/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='upload/img/flags/', verbose_name='Flag')),
                ('slug', models.CharField(max_length=2, verbose_name='Обозначение (en)')),
                ('header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст')),
                ('promo1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст в шапке (верх)')),
                ('promo2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст в шапке (низ)')),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_currency', to='geo.currency')),
                ('theme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_theme', to='decor.theme')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
