# Generated by Django 3.1.1 on 2022-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='rotate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Перемешивание топа'),
        ),
    ]
