# Generated by Django 3.1.1 on 2022-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_countries_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='currency',
            field=models.CharField(choices=[('€', '€'), ('$', '$')], default=None, max_length=10, null=True, verbose_name='Currency'),
        ),
    ]
