# Generated by Django 3.1.1 on 2022-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_countries_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='currency',
            field=models.CharField(choices=[(None, None), ('€', '€'), ('$', '$')], default=None, max_length=10, null=True, verbose_name='Currency'),
        ),
    ]
