# Generated by Django 3.1.1 on 2022-01-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20220111_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='currency',
        ),
    ]
