# Generated by Django 3.1.1 on 2022-01-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_remove_countries_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_currency', to='geo.currency'),
        ),
    ]
