# Generated by Django 3.1.1 on 2022-01-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0002_auto_20220112_1139'),
        ('geo', '0007_auto_20220112_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='theme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_theme', to='decor.theme'),
        ),
    ]
