# Generated by Django 3.1.1 on 2022-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_countries_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='promo1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст в шапке (верх)'),
        ),
        migrations.AddField(
            model_name='countries',
            name='promo2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст в шапке (низ)'),
        ),
    ]
