# Generated by Django 3.1.1 on 2022-01-12 11:37

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('bg_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет фона #RRGGBB')),
                ('bg_img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/custom/', verbose_name='Flag')),
                ('h_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет текста #RRGGBB')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
