# Generated by Django 3.1.1 on 2022-01-26 09:51

import colorfield.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('bg_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет фона #RRGGBB')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=7, null=True, samples=None, verbose_name='Основной цвет #RRGGBB')),
                ('h_color', colorfield.fields.ColorField(blank=True, default='#FFF000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет хедера #RRGGBB')),
                ('bg_img', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (desktop 1280px)')),
                ('bg_tab_img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (tablet 992px)')),
                ('bg_mob_img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (mobile 480px)')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/site_logos/', verbose_name='Логотип')),
                ('badge', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/site_badges/', verbose_name='Значек (справа от лого)')),
                ('icons_color', models.BooleanField(blank=True, default=False, verbose_name='Черно-белые иконки')),
                ('icon_to_top', models.BooleanField(blank=True, default=False, verbose_name='Иконка GO TO TOP')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
