# Generated by Django 3.1.1 on 2022-01-12 11:39

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bg_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение'),
        ),
    ]
