# Generated by Django 3.1.1 on 2022-01-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0002_auto_20220112_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Основной цвет #RRGGBB'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='h_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет хедера #RRGGBB'),
        ),
    ]
