# Generated by Django 3.1.1 on 2022-01-12 14:56

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0003_auto_20220112_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='upload/img/site_logos/', verbose_name='Логотип'),
        ),
    ]
