# Generated by Django 3.1.1 on 2022-01-13 10:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0004_theme_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет фона #RRGGBB'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, verbose_name='Основной цвет #RRGGBB'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='h_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, verbose_name='Цвет хедера #RRGGBB'),
        ),
    ]
