# Generated by Django 3.1.1 on 2022-01-18 07:40

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0006_auto_20220118_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bg_tab_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='upload/img/custom/', verbose_name='Фоновое изображение (tablet 992px)'),
        ),
    ]
