# Generated by Django 3.1.1 on 2022-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0009_auto_20220118_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon_to_top',
            field=models.BooleanField(blank=True, default=False, verbose_name='Иконка GO TO TOP'),
        ),
    ]
